<?php

/**
 * @file
 * Primary module hooks for Sims ChannelAdvisor module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function sims_channeladvisor_theme($existing, $type, $theme, $path) {
  return [
    'sims_channeladvisor_embed' => [
      'variables' => [
        'widget' => NULL,
        'show_title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function sims_channeladvisor_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  // Add our custom 'entity.commerce_product.where_to_buy' route as a link
  // template.
  $entity_types['commerce_product']->setLinkTemplate('where_to_buy', '/product/{commerce_product}/where-to-buy');
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 */
function sims_channeladvisor_preprocess_commerce_product__appliance(&$variables) {
  /** @var \Drupal\commerce_product\Entity\Product $product */
  $product = $variables['product_entity'];
  $variables['where_to_buy_url'] = [
    '#title' => t('Where To Buy'),
    '#type' => 'link',
    '#url' => $product->toUrl('where_to_buy'),
    '#attributes' => [
      'class' => [
        'use-ajax',
        'btn',
        'cr-uppercase'],
      'data-dialog-type' => 'modal',
    ],
    '#attached' => [
      'library' => ['core/drupal.dialog.ajax'],
    ],
  ];
}
